title: <p align="center"> Taher Dohadwala </p>

logo: "/images/headshot_circle.jpg"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/taher-dohadwala/">LinkedIn</a> |
  <a href="https://github.com/taher-dohadwala">GitHub</a>
  </p>
  
  <p align="justify">
  Passionate about self-directed learning and practical applications of data science and machine learning
  <br><br>
  Graduating December 2021, with a BS in Applied Statistics and a minor in CS and Entrepreneur and Innovation
  <br><br>
  Currently seeking entry level position as a Machine Learning Engineer or Data Scientist
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
