title: <p align="center"> Taher Dohadwala </p>

logo: "/images/download.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/taher-dohadwala/">LinkedIn</a> |
  <a href="https://github.com/taher-dohadwala">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing a BS degree in Applied Statistics at Purdue University.
  <br><br>
  I am passionate about self-directed learning and practical applications in Data Science and Deep Learning.
  <br><br>
  </p>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
